services:
  db-typing:
    image: postgres:18.0
    container_name: postgres_typing_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_DB: ${POSTGRESQL_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data-typing:/var/lib/postgresql
    networks:
      - back-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRESQL_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD:-my_secure_password_123}"
    volumes:
      - redis-data:/data
    networks:
      - back-net
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-my_secure_password_123}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  k1-typing-backend:
    build:
      context: ./k1-typing-backend
      dockerfile: Dockerfile
    container_name: k1-typing-backend
    ports:
      - "8080:8080"
    environment:
      POSTGRESQL_HOST: ${POSTGRESQL_HOST:-db-typing}
      POSTGRESQL_PORT: ${POSTGRESQL_PORT:-5432}
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DB: ${POSTGRESQL_DB}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      FRONTEND_HOST: ${FRONTEND_HOST}
      FRONTEND_PORT: ${FRONTEND_PORT_SECURITY}
    depends_on:
      db-typing:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - back-net

  k1-typing-frontend:
    build:
      context: ./k1-typing-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${BACKEND_URL:-http://localhost:8080}
        VITE_WEBSOCKET_URL: ${WEBSOCKET_URL:-}
    container_name: k1-typing-frontend
    ports:
      - "${FRONTEND_PORT:-5173}:${FRONTEND_PORT:-5173}"
    networks:
      - back-net

networks:
  back-net:
    driver: bridge

volumes:
  postgres-data-typing:
  postgres-data-sonar:
  redis-data: