spring:
  application:
    name: k1-typing-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRESQL_DB:-typing_db}
    username: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:strong_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  docker:
    compose:
      enabled: true
  jackson:
    deserialization:
      accept-empty-string-as-null-object: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:my_secure_password_123}
      database: 0

security:
  jwt:
    access-expiration-ms: 600000
    refresh-expiration-ms: 6000000

logging:
  level:
    ru.viktorgezz.k1_typing_backend: DEBUG